---
#gitLink: https://gist.github.com/aditya109/d48d70dd67c2065521c7952ed5c5209f
#destinationPath: D:\Projects\project_ideas.txt
gitLink: #enter the gist link <CANNOT BE NULL>
destinationPath:  #enter the path of the file into which the gist is to written <CANNOT BE NULL>